export const operationsEnglish = {
 'ops.autoSaved':'Saved automatically','ops.dueLabel':'due',
 'ops.weekOf':'Week of',
 'ops.selectApartment':'Select at least one apartment.','ops.keepConfirmed':'Keep at least one apartment when correcting this completed cleaning.','ops.invalidMoney':'Enter a valid PLN amount with no more than two decimal places.','ops.saveError':'Could not save this change.','ops.importError':'Could not read this backup.','ops.confirmError':'Could not confirm this cleaning.',
 'ops.reviewGuidance':'Untick apartments that were not cleaned. Confirm completed adds the remaining total to the real balance. Save plan keeps the cleaning unconfirmed.',
 'ops.bookingDog':'Dog in this booking', 'ops.bookingDogHelp':'Preselects the dog-cleaning bonus for the checkout cleaning. Saved cleanings keep their existing amounts; review them separately if needed.',
 'ops.owners':'Owners', 'ops.owner':'Owner', 'ops.unassigned':'Unassigned', 'ops.addOwner':'Add owner', 'ops.editOwner':'Edit owner', 'ops.ownerName':'Name / company', 'ops.phone':'Phone', 'ops.email':'Email', 'ops.address':'Address', 'ops.notes':'Notes', 'ops.save':'Save', 'ops.cancel':'Cancel', 'ops.edit':'Edit', 'ops.delete':'Delete', 'ops.archive':'Archive', 'ops.reactivate':'Reactivate', 'ops.active':'Active', 'ops.archived':'Archived', 'ops.searchOwners':'Search owners', 'ops.all':'All', 'ops.noOwners':'No owners yet.', 'ops.ownerRequired':'Enter an owner name.', 'ops.deleteOwner':'Delete owner?', 'ops.reassign':'Reassign apartments to', 'ops.deleteOwnerCopy':'Associated apartments and their history will be preserved. Choose a replacement owner or leave them unassigned.',
 'ops.customerPayment':'Customer payment', 'ops.paid':'Paid', 'ops.cashToCollect':'Cash to collect', 'ops.cashAmount':'Cash to collect (PLN)', 'ops.paymentNote':'Payment note', 'ops.cashRequired':'Enter a positive cash amount with at most two decimal places.', 'ops.paymentChanged':'Change the customer payment status or amount? Employee balances are not affected.',
 'ops.dog':'Dog-cleaning bonus', 'ops.dogAmount':'Dog bonus (PLN)', 'ops.defaultDog':'Default dog-cleaning bonus', 'ops.settings':'Cleaning settings', 'ops.bonusInvalid':'Enter a non-negative bonus with at most two decimal places.', 'ops.total':'Total', 'ops.cancelPlan':'Cancel planned cleaning', 'ops.cancelPlanCopy':'Remove this plan for {staff} on {date}? All assigned apartments will be freed. Expected earnings will be recalculated; confirmed earnings and payments will not change.', 'ops.confirmedChange':'This change recalculates confirmed earnings and the real balance. Existing payments are unchanged. Continue?',
 'ops.order':'Reorder apartments', 'ops.orderHelp':'Drag a card to its new position, or use its up/down buttons. Save to apply this category’s order.', 'ops.orderDirty':'Unsaved changes', 'ops.orderSaved':'Apartment order saved.', 'ops.discard':'Discard unsaved changes?', 'ops.up':'Move up', 'ops.down':'Move down', 'ops.drag':'Drag to reorder',
 'ops.employeeReport':'Employee work report', 'ops.employee':'Employee', 'ops.start':'From', 'ops.end':'Through', 'ops.includeMoney':'Include financial details (manager only)', 'ops.count':'{count} cleanings in this period', 'ops.signature':'Employee signature', 'ops.invalidPeriod':'Select an employee and a valid period.', 'ops.ownerReport':'Monthly owner report', 'ops.includeCharges':'Include cleaning charges', 'ops.noWork':'No cleanings in this period.', 'ops.ownerEmpty':'No apartments assigned to this owner.', 'ops.chooseOwner':'Select an owner.', 'ops.version':'Version {version}', 'ops.bonusBreakdown':'Base {base} + dog {bonus} = {total}', 'ops.checkout':'Checkout', 'ops.noResults':'No matching results.'
};
Object.assign(operationsEnglish, {'ops.correctConfirmed':'Correct confirmed cleaning','ops.confirmedUpdated':'Confirmed cleaning updated; balance recalculated.','ops.ownerCharge':'Owner cleaning charge (PLN, optional)','ops.ownerChargeHelp':'Separate from employee pay. Leave zero to omit charges from owner reports.','ops.notesHelp':'Cleaning instructions / notes','ops.demo':'Development demo — separate sample data'});
export const operationsPolish = {
 'ops.autoSaved':'Zapisano automatycznie','ops.dueLabel':'do wypłaty',
 'ops.weekOf':'Tydzień od',
 'ops.selectApartment':'Wybierz co najmniej jeden apartament.','ops.keepConfirmed':'Pozostaw co najmniej jeden apartament podczas poprawiania wykonanego sprzątania.','ops.invalidMoney':'Podaj prawidłową kwotę w PLN z maksymalnie dwoma miejscami po przecinku.','ops.saveError':'Nie udało się zapisać zmiany.','ops.importError':'Nie udało się odczytać kopii zapasowej.','ops.confirmError':'Nie udało się potwierdzić sprzątania.',
 'ops.reviewGuidance':'Odznacz apartamenty, które nie zostały posprzątane. Potwierdź wykonanie, aby dodać pozostałą kwotę do rzeczywistego salda. Zapisz plan, jeśli sprzątanie nie zostało jeszcze wykonane.',
 'ops.bookingDog':'Pies podczas pobytu', 'ops.bookingDogHelp':'Dodatek za sprzątanie po psie zostanie zaznaczony przy planowaniu sprzątania po wymeldowaniu. Zapisane zlecenia zachowają dotychczasowe kwoty — w razie potrzeby zmień je osobno.',
 'ops.owners':'Właściciele', 'ops.owner':'Właściciel', 'ops.unassigned':'Bez właściciela', 'ops.addOwner':'Dodaj właściciela', 'ops.editOwner':'Edytuj właściciela', 'ops.ownerName':'Imię i nazwisko / firma', 'ops.phone':'Telefon', 'ops.email':'E-mail', 'ops.address':'Adres', 'ops.notes':'Notatki', 'ops.save':'Zapisz', 'ops.cancel':'Anuluj', 'ops.edit':'Edytuj', 'ops.delete':'Usuń', 'ops.archive':'Archiwizuj', 'ops.reactivate':'Przywróć', 'ops.active':'Aktywni', 'ops.archived':'Archiwalni', 'ops.searchOwners':'Szukaj właściciela', 'ops.all':'Wszyscy', 'ops.noOwners':'Nie dodano jeszcze właścicieli.', 'ops.ownerRequired':'Podaj nazwę właściciela.', 'ops.deleteOwner':'Usunąć właściciela?', 'ops.reassign':'Przypisz apartamenty do', 'ops.deleteOwnerCopy':'Apartamenty i ich historia zostaną zachowane. Wybierz nowego właściciela lub pozostaw apartamenty bez właściciela.',
 'ops.customerPayment':'Płatność gościa', 'ops.paid':'Opłacona', 'ops.cashToCollect':'Gotówka do odebrania', 'ops.cashAmount':'Gotówka do odebrania (PLN)', 'ops.paymentNote':'Notatka dotycząca płatności', 'ops.cashRequired':'Podaj dodatnią kwotę z maksymalnie dwoma miejscami po przecinku.', 'ops.paymentChanged':'Zmienić status płatności gościa lub kwotę? Salda pracowników pozostaną bez zmian.',
 'ops.dog':'Dodatek za sprzątanie po psie', 'ops.dogAmount':'Dodatek za psa (PLN)', 'ops.defaultDog':'Domyślny dodatek za sprzątanie po psie', 'ops.settings':'Ustawienia sprzątania', 'ops.bonusInvalid':'Podaj nieujemną kwotę z maksymalnie dwoma miejscami po przecinku.', 'ops.total':'Razem', 'ops.cancelPlan':'Anuluj zaplanowane sprzątanie', 'ops.cancelPlanCopy':'Usunąć plan dla {staff} na {date}? Wszystkie przypisane apartamenty będą ponownie dostępne. Oczekiwane zarobki zostaną przeliczone; potwierdzone zarobki i wypłaty pozostaną bez zmian.', 'ops.confirmedChange':'Ta zmiana przeliczy potwierdzone zarobki i rzeczywiste saldo. Dotychczasowe wypłaty pozostaną bez zmian. Kontynuować?',
 'ops.order':'Ustaw kolejność apartamentów', 'ops.orderHelp':'Przeciągnij kartę na nowe miejsce lub użyj strzałek. Zapisz, aby zastosować kolejność w tej kategorii.', 'ops.orderDirty':'Niezapisane zmiany', 'ops.orderSaved':'Kolejność apartamentów została zapisana.', 'ops.discard':'Odrzucić niezapisane zmiany?', 'ops.up':'Przenieś wyżej', 'ops.down':'Przenieś niżej', 'ops.drag':'Przeciągnij, aby zmienić kolejność',
 'ops.employeeReport':'Raport pracy pracownika', 'ops.employee':'Pracownik', 'ops.start':'Od', 'ops.end':'Do (włącznie)', 'ops.includeMoney':'Uwzględnij rozliczenia (tylko dla kierownika)', 'ops.count':'Liczba sprzątań w tym okresie: {count}', 'ops.signature':'Podpis pracownika', 'ops.invalidPeriod':'Wybierz pracownika i prawidłowy zakres dat.', 'ops.ownerReport':'Miesięczny raport właściciela', 'ops.includeCharges':'Uwzględnij koszty sprzątania', 'ops.noWork':'Brak sprzątań w tym okresie.', 'ops.ownerEmpty':'Ten właściciel nie ma przypisanych apartamentów.', 'ops.chooseOwner':'Wybierz właściciela.', 'ops.version':'Wersja {version}', 'ops.bonusBreakdown':'Stawka {base} + dodatek {bonus} = {total}', 'ops.checkout':'Wymeldowanie', 'ops.noResults':'Brak pasujących wyników.'
};
Object.assign(operationsPolish, {'ops.correctConfirmed':'Popraw potwierdzone sprzątanie','ops.confirmedUpdated':'Zaktualizowano potwierdzone sprzątanie i przeliczono saldo.','ops.ownerCharge':'Opłata właściciela za sprzątanie (PLN, opcjonalnie)','ops.ownerChargeHelp':'Niezależna od wynagrodzenia pracownika. Wpisz zero, aby pominąć opłaty w raporcie właściciela.','ops.notesHelp':'Instrukcje sprzątania / notatki','ops.demo':'Wersja demonstracyjna — osobne dane przykładowe'});
